//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MinakortControls.rc
//
#define IDC_FOLDER_IMAGES               1003
#define IDD_UPLOAD_DLG                  1004
#define IDI_MINAKORTLOGO                1005
#define IDC_QUEUED_IMAGES               1006
#define IDR_MINAKORTCONTROLS            1007
#define IDC_FOUND2QUEUE                 1007
#define IDB_MINAKORT_TOP_LOGO           1007
#define IDR_QUEUEMENU                   1007
#define IDC_QUEUE2FOUND                 1008
#define IDC_TOP_IMAGE                   1009
#define IDB_MINAKORTWEBUPLOAD           1010
#define IDC_QUEUE2FOUND_ALL             1010
#define IDC_FOUND2QUEUE_ALL             1011
#define IDC_PROGRESSBAR                 1013
#define IDC_CHOOSESIZE_NOCHANGE         1014
#define IDC_CHOOSESIZE_LARGE            1015
#define IDB_ICON_INFO                   1016
#define IDD_INFO_UPLOADSTATUS           1016
#define IDC_CHOOSESIZE_MEDIUM           1016
#define IDD_INFO_ADDPHOTOSTIP           1017
#define IDB_OVERLAY_FINISHED            1017
#define IDC_CHOOSESIZE_SMALL            1017
#define IDS_MAIN_FOUNDPHOTOS            1018
#define IDD_EDITDETAILSDLG              1018
#define IDC_DLGICON                     1018
#define IDD_UPDATEDLG                   1018
#define IDS_MAIN_QUEUEDPHOTOS           1019
#define IDD_UPLOADSETTINGSDIALOG        1019
#define IDC_CHKREDUCEQUALITY            1019
#define IDS_MAIN_TITLE                  1020
#define IDS_EDIT_NAME                   1021
#define IDB_OVERLAY_RUNNING             1021
#define IDC_QUEUEHELP                   1021
#define IDS_EDIT_TEXT                   1022
#define IDR_MAIN_MENU                   1022
#define IDS_MAIN_PROGRESSBARSTART       1023
#define IDR_MAINACC                     1023
#define IDC_USERNAME                    1023
#define IDS_MAIN_STARTINGUPLOAD         1024
#define IDC_PASSWORD                    1024
#define IDS_MAIN_STARTINGWITHNOTHING    1025
#define IDD_LOGINDIALOG                 1025
#define IDC_CHK_SAVE                    1025
#define IDS_MAIN_STARTINGCAPTION        1026
#define IDB_MINAKORT_TOP_LOGO_BLUE      1026
#define IDS_TIP_START_TITLE             1027
#define IDC_RESULT                      1027
#define IDR_FOLDERMENU                  1027
#define IDS_TIP_START_TEXT              1028
#define IDC_COMPRESSIONRECOMMEDATION    1028
#define IDS_TIP_START_BTN1              1029
#define IDC_UPDATEPROGRESS              1029
#define IDS_TIP_START_BTN2              1030
#define IDC_UPDATEPROGRESSTEXT          1030
#define IDD_SHARING_DIALOG              1030
#define IDS_MAIN_NONEFOUND              1031
#define IDC_LIST1                       1031
#define IDS_MAIN_ADDINGCAPTION          1032
#define IDC_CHECK1                      1032
#define IDC_LETFRIENDS_ADD              1032
#define IDS_MAIN_QUEUEHELP_TITLE        1033
#define IDC_SHARETOFRIENDS              1033
#define IDB_GROUPICON                   1033
#define IDS_MAIN_QUEUEHELP_TEXT         1034
#define IDC_SHARELIST                   1034
#define IDS_MAIN_INPROGRESS_ABORTBTN    1035
#define IDS_MAIN_INPROGRESS_RUNINBAKGROUNDBTN 1036
#define IDC_SHARING_ICON                1036
#define IDS_LOGIN_INVALID_ENTRY         1037
#define IDC_CATEGORYNAME                1037
#define IDS_LOGIN_CAPTION               1038
#define IDS_MAIN_ABORTQUESTION          1039
#define IDC_BTNSHARESETTINGS            1039
#define IDS_VALUE2STR_L1                1040
#define IDS_LOGIN_WRONGUSERNAMEPWD      1041
#define IDS_LOGIN_SERVERERROR           1042
#define IDS_VALUE2STR_V                 1043
#define IDS_STATUS_TITLE_1              1044
#define IDS_STATUS_TITLE_N              1045
#define IDS_STATUS_SIZE                 1046
#define IDS_STATUS_SPEED                1047
#define IDS_STATUS_REMAINING_1N         1048
#define IDS_STATUS_REMAINING_NN         1049
#define IDS_MAIN_UPLOADRESULT_NETWORKERROR 1050
#define IDS_MAIN_UPLOADRESULT_GENERALERROR 1051
#define IDS_MAIN_UPLOADRESULT_FINISHED  1052
#define IDS_MAIN_UPLOADRESULT_ABORTED   1053
#define IDS_PROGRESSBAR_INDETERMINATE   1054
#define IDS_PROGRESSBAR_1               1055
#define IDS_PROGRESSBAR_1P              1056
#define IDS_PROGRESSBAR_N               1057
#define IDS_QUOTARECOMMENDATION_ANY     1058
#define IDS_QUOTARECOMMENDATION_LL      1059
#define IDS_QUOTARECOMMENDATION_LS      1060
#define IDS_QUOTARECOMMENDATION_ML      1061
#define IDS_QUOTARECOMMENDATION_MS      1062
#define IDS_QUOTARECOMMENDATION_SL      1063
#define IDS_QUOTARECOMMENDATION_SS      1064
#define IDS_QUOTARECOMMENDATION_NONE    1065
#define IDS_MAIN_CLIENTOLD_TEXT         1066
#define IDS_MAIN_ERROR                  1067
#define IDS_STARTUP_JOBSMISSING         1068
#define IDS_STARTUP_RESTORINGJOBS       1069
#define IDS_CLEAR_LIST                  1070
#define IDS_CLEAR_LISTQUESTION          1071
#define IDS_UPDATE_STARTING             1072
#define IDS_UPDATE_TOOOLDCLIENT         1073
#define IDS_UPDATE_NEWVERSIONAVAILABLETEXT 1074
#define IDS_UPDATE_TOOOLDCLIENT_CAPTION 1075
#define IDS_UPDATE_NEWVVERSIONAVAILABLE 1076
#define IDS_UPDATE_INSTALLINGCAPTION    1077
#define IDS_UPDATE_INSTALLATIONFINISHED 1078
#define IDS_UPDATE_INSTALLATIONFAILED   1079
#define IDS_UPDATE_SERVERMESSAGECAPTION 1080
#define IDS_ERROROCCURED                1081
#define IDS_ERROROCCURED_CAPTION        1082
#define IDS_UPDATEERROR_COMM            1083
#define IDS_UPDATEERROR_FILE            1084
#define IDS_UPDATEERROR_OLDCLIENT       1085
#define IDS_UPDATEERROR_BINARY          1086
#define IDS_UPDATEERROR_REG             1087
#define IDS_UPDATEERROR_UNKNOWN         1088
#define IDS_CLEARLIST                   1089
#define IDS_CLEAR_FINISHEDLIST          1090
#define IDS_CLEAR_QUEUE                 1091
#define IDS_INSTALLNOADMIN              1092
#define IDS_INSTALLNOADMINCAPTION       1093
#define IDS_SHARE_NOCONTACT             1094
#define IDS_NETWORKPROBLEM_CAPTION      1095
#define IDS_SHARE_NOSECURITYPERMISSION  1096
#define IDS_SHARE_CHOOSING_CAPTION      1097
#define IDS_SHARE_NOADDPERMISSION       1098
#define IDS_SHARE_DOUBLENAME            1099
#define IDS_SHARE_DOUBLENAME_CAPTION    1100
#define IDS_SHARE_CLM_NAME              1101
#define IDS_SHARE_CLM_DETAILS           1102
#define IDS_SHARE_ACT_REMOVE            1103
#define IDS_SHARE_NAMELOOKUPFAIL        1104
#define IDS_SHARE_NAMELOOKUP_FOUND_N    1105
#define IDS_SHARE_NAMELOOKUP_FOUND_0    1106
#define IDS_SHARE_REMOVEALLNAMES        1107
#define IDS_CLEARLIST_CAPTION           1108
#define IDS_MAIN_CANTEDITSHAREWHILEUPLOADING 1109
#define IDS_MAIN_UPLOADINPROGRES        1110
#define ID_GR_BL                        32771
#define ID_STYLE_GREEN                  32775
#define ID_STYLE_BLUE                   32776
#define ID_ESCAPE                       32777
#define ID_RETURN                       32779
#define ID_CLEAR_FOLDERLIST             32781
#define ID_CLEAR_LIST                   32783
#define ID_REMOVE_FOLDERITEM            32785
#define ID_QUEUE_DELETEITEM             32789
#define ID_CLEAR_FINISHED               32790
#define ID_CLEAR_QUEUE                  32791
#define IDS_MAIN_UPLOADINGCAPTION       58117
#define IDS_MAIN_ABORTUPLOADQUESTION    58118

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1034
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           1095
#endif
#endif
